#!/bin/sh
if [ ! -d /etc/xdg/menus/applications-merged ]; then
    mkdir -p /etc/xdg/menus/applications-merged
fi
cp /opt/interact/desktop/luidia.menu /etc/xdg/menus/applications-merged/luidia.menu
# This seems to get Ubuntu (and other Gnome desktops?) to notice the menu file
killall gnome-panel
#cp /etc/xdg/menus/applications-merged/ebeam.menu /etc/xdg/menus/applications-merged/luidia.menu
ln -s /opt/interact/desktop/luidia-scrapbook.desktop /usr/share/applications
# KDE won't update the menu until you run the following
if [ -e /usr/bin/kbuildsycoca ]; then
	/usr/bin/kbuildsycoca
fi

#install X mouse driver
####if [ -d /usr/lib/xorg/modules/drivers ]; then
####    ln -s /opt/interact/bin/ebeam_drv.so /usr/lib/xorg/modules/drivers/ebeam_drv.so

####    /opt/interact/bin/ebeam-xconf.pl /etc/X11/xorg.conf install

####    if [ ! -e /etc/X11/xorg.conf ]; then
####        echo "X not configured to use eBeam X mouse driver"
####    else
####	echo "Need to restart X to enable mouse control (Ctrl-Alt-Backspace or Ctrl-Alt-Delete, click Restart)"
####    fi

####else
####    echo "ebeam_drv.so not installed"
####fi

############ NEW DIVA #########################
ln -fs /opt/diva/eBeam_Stylus_Driver /usr/sbin/eBeam_Stylus_Driver
ln -fs /opt/diva/eBeam_Stylus_Preferences /usr/bin/eBeam_Stylus_Preferences
ln -fs /opt/diva/eBeam_Calibration /usr/bin/eBeam_Calibration

ln -fs /opt/diva/ebeam-stylus-driver /etc/init.d/ebeam-stylus-driver

update-rc.d ebeam-stylus-driver defaults 15

invoke-rc.d ebeam-stylus-driver start

/opt/diva/update-icon-permissions.sh

MAJOR_VERSION="`lsb_release -a 2>&1 | grep Release | awk '{print \$2;}' | awk -F. '{print \$1;}'`"

echo "ubuntu version: $MAJOR_VERSION"

if [[ $MAJOR_VERSION -ge 12 ]]; then
    killall unity-2d-panel
fi

USERS=`ps aux | grep nautilus | grep -v grep | awk '{ print $1 }'`

export DISPLAY=:0

# start mouse driver for all currently logged on users
# also, update their unity preferences to allow the stylus preferences icon to show up
for user in $USERS; do
####    su $user -c "nohup /opt/diva/ebeam-mouse-driver "
####    su $user -c "nohup /opt/diva/delayed-preferences.sh &"
    if [[ $MAJOR_VERSION -ge 12 ]]; then
	su $user -c "nohup unity-2d-panel &"
    fi
done

exit 0
