#!/bin/sh
# remove links to /opt/interact/bin
rm -f /usr/bin/interact
####rm -f /usr/sbin/ebeam-server
####rm -f /usr/lib/xorg/modules/drivers/ebeam_drv.so
# remove menu item
rm -f /etc/xdg/menus/applications-merged/luidia.menu

rm -Rf /opt/interact

# remove invocation of eBeamIO
####sed -i s#LD_LIBRARY_PATH=/opt/interact/bin\ /opt/interact/bin/eBeamIO\ \&## /etc/X11/Xsession.d/55gnome-session_gnomerc

###################### NEW DIVA ###################
update-rc.d ebeam-stylus-driver remove

exit 0

