#!/bin/sh
# remove initscripts
####if [ -x /etc/init.d/interact ]; then
####	if which invoke-rc.d >/dev/null 2>&1; then
####	    invoke-rc.d interact stop
####	else
####	    /etc/init.d/interact stop
####	fi
####	rm -f /etc/init.d/interact
####	if which update-rc.d >/dev/null 2>&1; then
####	    update-rc.d interact remove
####	else
####	    for RUNLEVEL in 2 3 5; do
####		rm -f /etc/rc$RUNLEVEL.d/S[0-9][0-9]interact
####	    done
####	fi
####fi
# clean xorg.conf
####if [ -w /etc/X11/xorg.conf ]; then
####    /opt/interact/bin/ebeam-xconf.pl /etc/X11/xorg.conf remove
####fi

#################### NEW DIVA ####################

if ps ax | grep -v grep | grep Scrapbook
then
    killall /opt/interact/bin/eBeamScrapbook
fi
if ps ax | grep -v grep | grep ToolPalette
then
    killall /opt/interact/bin/eBeamToolPalette/eBeamToolPalette
fi
if ps ax | grep -v grep | grep eBeam_Stylus_Preferences
then
    killall /opt/diva/eBeam_Stylus_Preferences
fi

if ps ax | grep -v grep | grep eBeam_Calibration
then
    killall /opt/diva/eBeam_Calibration
fi

if ps ax | grep -v grep | grep eBeam_Mouse_Driver
then
    killall /opt/diva/eBeam_Mouse_Driver
fi

invoke-rc.d ebeam-stylus-driver stop
rm -f /etc/init.d/ebeam-stylus-driver

if [ -e /usr/bin/eBeam_Calibration ]; then
rm "/usr/bin/eBeam_Calibration"
fi

if [ -e /usr/sbin/eBeam_Stylus_Driver ]; then
rm "/usr/sbin/eBeam_Stylus_Driver"
fi

if [ -e /usr/bin/eBeam_Stylus_Preferences ]; then
rm "/usr/bin/eBeam_Stylus_Preferences"
fi

exit 0
